#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-airline
Version  : 0.7
Release  : 2
URL      : https://github.com/airlift/airline/archive/0.7.tar.gz
Source0  : https://github.com/airlift/airline/archive/0.7.tar.gz
Source1  : https://repo1.maven.org/maven2/io/airlift/airline/0.7/airline-0.7.jar
Source2  : https://repo1.maven.org/maven2/io/airlift/airline/0.7/airline-0.7.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-airline-data = %{version}-%{release}
Requires: mvn-airline-license = %{version}-%{release}

%description
Airline
=======
Airline is a Java annotation-based framework for parsing Git like command line structures.

%package data
Summary: data components for the mvn-airline package.
Group: Data

%description data
data components for the mvn-airline package.


%package license
Summary: license components for the mvn-airline package.
Group: Default

%description license
license components for the mvn-airline package.


%prep
%setup -q -n airline-0.7

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-airline
cp license.txt %{buildroot}/usr/share/package-licenses/mvn-airline/license.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/airline/0.7
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/io/airlift/airline/0.7/airline-0.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/airline/0.7
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/io/airlift/airline/0.7/airline-0.7.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/io/airlift/airline/0.7/airline-0.7.jar
/usr/share/java/.m2/repository/io/airlift/airline/0.7/airline-0.7.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-airline/license.txt
